// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using DBCore.Models;

//#nullable disable

namespace DBCore.Data
{
    public partial class WarehousesContext : DbContext
    {
        public WarehousesContext()
        {
        }

        public WarehousesContext(DbContextOptions<WarehousesContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Turkish_CI_AS");

            modelBuilder.Entity<Location>(entity =>
            {
                entity.ToTable("location");

                entity.Property(e => e.Id).HasColumnName("_id");

                entity.Property(e => e.Lat)
                    .HasMaxLength(500)
                    .IsUnicode(false)
                    .HasColumnName("lat");

                entity.Property(e => e.Long)
                    .HasMaxLength(500)
                    .IsUnicode(false)
                    .HasColumnName("long");

                entity.Property(e => e.Name)
                    .HasMaxLength(200)
                    .HasColumnName("name");
            });

            modelBuilder.Entity<Vehicle>(entity =>
            {
                entity.ToTable("vehicle");

                entity.Property(e => e.Id).HasColumnName("_id");

                entity.Property(e => e.DateAdded)
                    .HasMaxLength(200)
                    .HasColumnName("date_added");

                entity.Property(e => e.Licensed).HasColumnName("licensed");

                entity.Property(e => e.Make)
                    .HasMaxLength(150)
                    .HasColumnName("make");

                entity.Property(e => e.Model)
                    .HasMaxLength(150)
                    .HasColumnName("model");

                entity.Property(e => e.Price)
                    .HasColumnType("decimal(18, 18)")
                    .HasColumnName("price");

                entity.Property(e => e.WarehousesId).HasColumnName("warehouses_id");

                entity.Property(e => e.YearModel).HasColumnName("year_model");

                entity.HasOne(d => d.Warehouses)
                    .WithMany(p => p.Vehicles)
                    .HasForeignKey(d => d.WarehousesId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Vehicle_warehouses");
            });

            modelBuilder.Entity<Warehouse>(entity =>
            {
                entity.ToTable("warehouse");

                entity.Property(e => e.Id).HasColumnName("_id");

                entity.Property(e => e.LocationId).HasColumnName("location_id");

                entity.Property(e => e.Name)
                    .HasMaxLength(100)
                    .HasColumnName("name");

                entity.HasOne(d => d.Location)
                    .WithMany(p => p.Warehouses)
                    .HasForeignKey(d => d.LocationId)
                    .HasConstraintName("FK_warehouses_location");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}