// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DBCore.Models
{
    public partial class Vehicle
    {
        public int Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int? YearModel { get; set; }
        public decimal? Price { get; set; }
        public bool? Licensed { get; set; }
        public string DateAdded { get; set; }
        public int WarehousesId { get; set; }

        public virtual Warehouse Warehouses { get; set; }
    }
}